export const INDIAN_CITIES = [
  "Agra",
  "Ahmedabad",
  "Ajmer",
  "Akola",
  "Aligarh",
  "Allahabad (Prayagraj)",
  "Amravati",
  "Amritsar",
  "Anantapur",
  "Asansol",
  "Aurangabad (Chhatrapati Sambhajinagar)",
  "Bareilly",
  "Belgaum",
  "Bengaluru (Bangalore)",
  "Bhagalpur",
  "Bhilai",
  "Bhiwandi",
  "Bhopal",
  "Bhubaneswar",
  "Bikaner",
  "Bokaro",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Cuttack",
  "Dehradun",
  "Delhi / NCR",
  "Dhanbad",
  "Dhule",
  "Durgapur",
  "Erode",
  "Faridabad",
  "Firozabad",
  "Ghaziabad",
  "Gorakhpur",
  "Gulbarga",
  "Guntur",
  "Gurugram (Gurgaon)",
  "Guwahati",
  "Gwalior",
  "Hubli-Dharwad",
  "Hyderabad",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jalgaon",
  "Jammu",
  "Jamnagar",
  "Jamshedpur",
  "Jhansi",
  "Jodhpur",
  "Kakinada",
  "Kalyan-Dombivli",
  "Kanpur",
  "Kharagpur",
  "Kochi",
  "Kolhapur",
  "Kolkata",
  "Kollam",
  "Kota",
  "Kozhikode",
  "Kurnool",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Mangaluru (Mangalore)",
  "Meerut",
  "Moradabad",
  "Mumbai",
  "Muzaffarnagar",
  "Mysuru (Mysore)",
  "Nagpur",
  "Nanded",
  "Nashik",
  "Navi Mumbai",
  "Nellore",
  "New Delhi",
  "Noida",
  "Panaji",
  "Patiala",
  "Patna",
  "Puducherry",
  "Pune",
  "Raipur",
  "Rajahmundry",
  "Rajkot",
  "Ranchi",
  "Rourkela",
  "Saharanpur",
  "Salem",
  "Sangli",
  "Shillong",
  "Shimla",
  "Siliguri",
  "Solapur",
  "Srinagar",
  "Surat",
  "Thane",
  "Thiruvananthapuram",
  "Thrissur",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Udaipur",
  "Ujjain",
  "Vadodara",
  "Varanasi",
  "Vasai-Virar",
  "Vijayawada",
  "Visakhapatnam",
  "Warangal"
].sort((a, b) => a.localeCompare(b));
